### PR TITLE
Update sed to version 4.4

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- re-render with conda-smithy
- add `gettext` requirement for NLS support

### CODE REVIEW

**Comment by jakirkham** [comment]
Apparently it is [known]( http://www.linuxfromscratch.org/lfs/view/development/chapter06/sed.html ) that `testsuite/panic-tests.sh` fails, would add a patch for `Makefile.in` to skip that test.

**Comment by nsoranzo** [comment]
@jakirkham Indeed, it's been reported upstream https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25692 and fixed for the next release in commit https://git.savannah.gnu.org/cgit/sed.git/commit/?id=b092d4a6c07b25f743d302b05c308325edcfc599 . I'll fix this in a bit.

**Comment by jakirkham** [comment]
Ah ok good. Was searching for an upstream bug report, but my Google-fu was weak. If there is a fix, maybe patching the test would be better.

**Comment by nsoranzo** [comment]
@jakirkham I tried the upstream commit as a patch, but it seems that was not enough to fix the test, I guess I'll have to skip it as you suggested initially since I'm not able to reproduce the bug locally.

**Comment by jakirkham** [comment]
Hmm...where did CircleCI go? Closing/reopening to retrigger.

**Comment by jakirkham** [comment]
Weird. It seems I can't do anything to fix it. 😕 Could you please repush @nsoranzo?

**Comment by nsoranzo** [comment]
I've also tried to close and reopen with no clock. I've tried to change a commit and rebase, still no luck. Should I try closing this PR and opening a fresh one?

**Comment by jakirkham** [comment]
Sure, let's give that a try. Have you changed any setting w.r.t. CircleCI recently?

**Pull request closed without merging**
